# Generated by Django 3.2.7 on 2021-11-28 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('community', models.CharField(choices=[('Mortal Kombat', 'MORTAL KOMBAT'), ('Guilty Gear', 'GUILTY GEAR'), ('Smash', 'SMASH'), ('Street Fighter', 'STREET FIGHTER')], default='Mortal Kombat', max_length=20)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('Friendly', 'FRIENDLY'), ('Exhibition', 'EXHIBITION'), ('Tournament', 'TOURNAMENT')], default='Friendly', max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(related_name='events_dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='events_likes', to=settings.AUTH_USER_MODEL)),
                ('signed_up', models.ManyToManyField(related_name='events_signed_up', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
