# Generated by Django 3.2.9 on 2021-11-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='community',
            field=models.CharField(choices=[('Mortal Kombat', 'MORTAL KOMBAT'), ('Guilty Gear', 'GUILTY GEAR'), ('Smash', 'SMASH'), ('Street Fighter', 'STREET FIGHTER'), ('All', 'ALL')], default='Mortal Kombat', max_length=20),
        ),
    ]
