# Generated by Django 3.2.9 on 2021-11-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_events_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='community',
            field=models.CharField(choices=[('Mortal Kombat', 'MORTAL KOMBAT'), ('Guilty Gear', 'GUILTY GEAR'), ('Smash', 'SMASH'), ('Street Fighter', 'STREET FIGHTER'), ('All', 'ALL')], default='All', max_length=20),
        ),
    ]
