# Generated by Django 3.2.9 on 2021-11-30 12:02

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_events_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)]),
        ),
    ]
