# Generated by Django 3.2.9 on 2021-12-02 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_auto_20211202_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='event_comment_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='event_comment_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
