# Generated by Django 3.2.7 on 2021-11-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.TextField(default='all'),
        ),
    ]
