# Generated by Django 3.2.9 on 2021-11-28 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_post_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(related_name='post_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='community',
            field=models.CharField(choices=[('Mortal Kombat', 'MORTAL KOMBAT'), ('Guilty Gear', 'GUILTY GEAR'), ('Smash', 'SMASH'), ('Street Fighter', 'STREET FIGHTER'), ('All', 'ALL')], default='All', max_length=20),
        ),
    ]
