# Generated by Django 3.2.9 on 2021-12-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_templateimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateimages',
            name='image',
            field=models.ImageField(upload_to='template-images'),
        ),
    ]
