# Generated by Django 3.2.9 on 2021-12-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211202_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
